version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/server/node-server-app"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "16:00"
  - package-ecosystem: "npm"
    directory: "/client/react-client-app"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "16:00"
  - package-ecosystem: "docker"
    directory: "/database"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "16:00"
  - package-ecosystem: "docker"
    directory: "/server/node-server-app"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "16:00"
  - package-ecosystem: "docker"
    directory: "/client/react-client-app"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "16:00"
