services:
  client:
    build:
      context: ./client/react-client-app
      dockerfile: Dockerfile
    image: meetonline-client:latest
    container_name: meetonline-client
    env_file:
      - ./client/react-client-app/docker.env
    ports:
      - "5173:5173"
    depends_on:
      - server
    restart: no

  server:
    build:
      context: ./server/node-server-app
      dockerfile: Dockerfile
    image: meetonline-server:latest
    container_name: meetonline-server
    env_file:
      - ./server/node-server-app/docker.env
    ports:
      - "9006:9006"
      - "9443:9443"
    depends_on:
      - database
    volumes:
      - server_uploads:/usr/src/app/uploads
      - server_certs:/usr/src/app/certs
      - server_tmp:/usr/src/app/tmp
    restart: no

  database:
    build:
      context: ./database
      dockerfile: Dockerfile
    image: meetonline-database:latest
    container_name: meetonline-database
    env_file:
      - ./database/docker.env
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql:Z
    restart: no

volumes:
  db_data:
  server_uploads:
  server_certs:
  server_tmp:

