services:
  proxy:
    image: nginx:stable
    ports:
      - 443:443
    volumes:
      - ./proxy/nginx.conf:/etc/nginx/nginx.conf:ro
    restart: no

  client:
    build: ./client/react-client-app
    command: ["npm", "run", "dev", "--", "--host"]
    ports:
      - 5173:5173
    env_file:
      - ./client/react-client-app/docker.env
    depends_on:
      - server
    volumes:
      - ./client/react-client-app:/app
    restart: no
    develop:
      watch:
        - path: ./client/react-client-app
          action: rebuild

  server:
    build:
      context: ./server/node-server-app
      dockerfile: Dockerfile
    image: meetonline-server:latest
    container_name: meetonline-server
    env_file:
      - ./server/node-server-app/docker.env
    ports:
      - 9006:9006
      - 9443:9443
    depends_on:
      database:
        condition: service_healthy
    volumes:
      - server_uploads:/server/uploads
      - server_certs:/server/certs
      - server_tmp:/server/tmp
    restart: no

  database:
    image: postgres:18.1
    container_name: meetonline-database
    env_file:
      - path: ./database/docker.env
        required: true
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql
      - ./database/init/schema.sql:/docker-entrypoint-initdb.d/init.sql
    restart: no
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  db_data:
  server_uploads:
  server_certs:
  server_tmp:
  client_certs:
